### ISSUE TITLE
Deploy stuck forewer if `ovirt_engine_setup_accept_defaults` not true

### ISSUE THREAD

**Issue by Arano-kai** [oVirt/ovirt-ansible-hosted-engine-setup#101]
Breaks by e89f8597bdce5730bf9e5035d7de41f18c11ef81 and indirectly by 839c74ea0d92b859472aa7970378df995fc4a543.
Reason:
`ovirt_engine_setup_accept_defaults` is part of `ovirt.engine-setup` and by default `false`, with lead to stuck at `Run engine-setup with answerfile`.

**Comment by tiraboschi** [comment]
As you can see in
https://github.com/oVirt/ovirt-ansible-engine-setup/blob/master/tasks/engine_setup.yml#L53
now ovirt.engine-setup always pass --accept-defaults and ovirt_engine_setup_accept_defaults doesn't exist anymore there, that's why we removed it.
It has been removed with:
https://github.com/oVirt/ovirt-ansible-engine-setup/pull/35
on Dec 19
The issue is probably just about requiring here a version of ovirt.engine-setup recent enough.

ovirt_repositories_ovirt_release_rpm instead is needed if and only if the user sets 
```
  roles:
    - role: ovirt.repositories
```
in his playbook.

The solution to this is using static imports and hosts delegation in order to let the user deploy with a much simpler playbook as for #20

**Comment by Arano-kai** [comment]
Installed from galaxy, whist is still 1.1.5
Thank you for the clarification :)
